use sakila;
#1. Retrieve the total revenue generated for each film category.
select fc.category_id, sum(p.amount) as 'Total Revenue' from film_category fc join film f on fc.film_id=f.film_id join inventory i 
on i.film_id=f.film_id
join rental r on r.inventory_id=i.inventory_id join payment p on p.rental_id=r.rental_id group by fc.category_id;

#2. Determine the count of rentals for each customer.
select count(rental_id), c.customer_id from customer c join rental on rental.customer_id=c.customer_id group by customer_id;

#3. Calculate the average rental duration (in days) for each film.
select film_id, avg(rental_duration) from film group by film_id;

#4. Find the total revenue generated for each month.
select month(payment_date), sum(amount) from payment group by month(payment_date);

#5. Determine the total revenue generated by each store.
select st.store_id,sum(p.amount) as "Total Revenue" from store st join staff s on st.store_id=s.store_id 
join payment p on p.staff_id=s.staff_id group by st.store_id;

#6. Calculate the count of rentals handled by each staff member.
select st.staff_id, count(r.rental_id) from staff st join store s on st.store_id=s.store_id 
join customer c on c.store_id=s.store_id join rental r on r.customer_id=c.customer_id group by staff_id;

#7. Compute the average rental rate for each film category.
select fc.category_id,avg(f.rental_rate) from film_category fc join film f on fc.film_id=f.film_id group by fc.category_id;

#8. Determine the count of rentals for each film.
select count(r.rental_id), f.film_id from rental r join inventory i on i.inventory_id=r.inventory_id 
join film f on i.film_id=f.film_id group by f.film_id;

#9. Retrieve the total revenue generated for each city.
select c.city_id, sum(p.amount) from city c join address a on a.city_id=c.city_id join customer ct on ct.address_id=a.address_id 
join payment p on p.customer_id=ct.customer_id group by c.city_id;

#10. Calculate the count of rentals for each film language.
select count(r.rental_id), l.language_id from rental r join inventory i on i.inventory_id=r.inventory_id 
join film f on f.film_id=i.film_id join language l on l.language_id=f.language_id group by l.language_id;
select * from language;